Removed workaround for https://youtrack.jetbrains.com/issue/IDEA-315427.
It is not working because of a clash between the kotlin-stdlib library
versions, that cause:

```
Caused by: java.lang.NoSuchMethodError: 'byte[] kotlin.collections.ArraysKt.copyInto(byte[], byte[], int, int, int)'
```

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>