Issue #670 - Document CometD embedded.
Added note about NoSuchMethodError thrown at startup, caused by
a Jetty dependency with the "hybrid" classifier.